#!/bin/sh


#branch
if [ "$2" == "" ]; then
    branch=`git rev-parse --abbrev-ref HEAD`
else
    branch="$2"
fi

if [ "$1" == "" ]; then

git log --pretty=format:"%h - %an, %ar : %s" --graph --max-count=5
#git log --pretty=format:"%h - %an, %ar : %s" --graph "$branch"

else

git log --pretty=format:"%h - %an, %ar : %s" --graph --max-count=$1 "$branch"

fi

