#!/bin/sh


#current branch
currBranch=`git rev-parse --abbrev-ref HEAD`

if [ "$1" == "" ]; then

git log --pretty=format:"%h - %an, %ar : %s" --graph "$currBranch"

else

git log --pretty=format:"%h - %an, %ar : %s" --graph --max-count=$1 "$currBranch"

fi

