#!/bin/sh -x

#publish current branch to dev3 upstream

if [ "$1" == "" ]; then
  branch="dev3"
else
  branch="$1"
fi

#current branch
currBranch=`git rev-parse --abbrev-ref HEAD`

#discern main repo
chkRepo=`git config --get remote.origin.url|grep Blinds|wc -l`
if [ "$chkRepo" -eq "0" ]; then
 repo="upstream"
else
 repo="origin"
fi

#sync master first
git checkout master
git fetch origin master
git reset --hard $repo/master
git clean -fxd
git push origin master

#now publish
git checkout "$currBranch"
git rebase master
git push --force $repo "env/$branch"

