#!/bin/sh -x

#publish current branch to uat1 upstream

if [ "$1" == "" ]; then
  branch="uat1"
else
  branch="$1"
fi

#sync master first
git checkout master
git fetch origin master
git reset --hard upstream/master
git clean -fxd
git push origin master

#now publish
git checkout "env/$branch"
git rebase master
git push upstream "env/$branch"
