#!/bin/sh -x

#this resets your tracking branch to exactly what it is on remote

if [ "$1" == "" ]; then
 echo "Missing repo."
 exit
fi
if [ "$2" == "" ]; then
 echo "Missing branch."
 exit
fi

#current branch
currBranch=`git rev-parse --abbrev-ref HEAD`

git fetch $1 "$2"
git reset --hard HEAD $1/$2 
git clean -fxd

git checkout "$currBranch"

