#!/bin/sh -x

#this resets your tracking branch to exactly what it is on local branch

if [ "$1" == "" ]; then
 echo "Missing branch."
 exit
fi

#current branch
currBranch=`git rev-parse --abbrev-ref HEAD`

#git fetch $1 "$2"
git reset --hard HEAD $1

git checkout "$currBranch"

