#!/bin/sh -x

#reset tracking and remote branches to master; dev1 is default

if [ "$1" == "" ]; then
  branch="dev1"
else
  branch="$1"
fi

#beg: old stuff
#git checkout master
#git branch -D env/dev1
#git checkout -b env/dev1 origin/env/dev1
#git branch --track env/dev1 origin/env/dev1
#end: old stuff

git checkout master
git pull origin master
git checkout "env/$branch"
git fetch origin "env/$branch"
git reset --hard master
git clean -fxd
git push origin "env/$branch"
