#!/bin/sh -x

branches="$1"
if [ "$branches" == "" ]; then
  branches=""
else
  branches="$1"
fi

#master#{{{

#echo "-------------------------------------"
#echo "reset Remote + Remote Tracking Branches: master"
#echo "-------------------------------------"
#echo ""

git checkout master
git fetch origin master
git reset --hard upstream/master
git clean -fxd
git push origin master

#master}}}
#branches#{{{

if [ "$branches" != "" ];then

for branch in `echo $branches|sed -e 's/,/ /g'`; do

#echo "-------------------------------------"
#echo "reset Remote + Remote Tracking Branches: $branch"
#echo "-------------------------------------"
#echo ""

git checkout env/$branch
git fetch origin env/$branch
git reset --hard upstream/env/$branch
git clean -fxd
git push origin env/$branch
#git reset --hard origin/env/$branch

done

fi

#branches#}}}

