#!/bin/sh -x

#reset tracking branch to its remote version; dev3 is the default

if [ "$1" == "" ]; then
  branch="env/dev3"
else
  branch="$1"
fi

git checkout master
git pull origin master
git checkout "$branch"
git fetch origin "$branch"
git reset --hard "origin/$branch"
git clean -fxd
