#!/bin/sh -x

#reset current branch to master

#current branch
currBranch=`git rev-parse --abbrev-ref HEAD`

git checkout master
git pull origin master
git reset --hard master
git clean -fxd
git checkout "$currBranch"

