#!/bin/sh


#current branch
currBranch=`git rev-parse --abbrev-ref HEAD`

if [ "$1" != "" ]; then
  cnt="$1"
fi
if [ "$2" == "" ]; then
  repo="origin" 
else
  repo="$2" 
fi
if [ "$3" == "" ]; then
  branch="$currBranch"
else
  branch="$3"
fi

git fetch "$repo" "$branch"

if [ "$cnt" == "" ]; then

echo git log --pretty=format:"%h - %an, %ar : %s" --graph "$repo/$branch"

else

echo git log --pretty=format:"%h - %an, %ar : %s" --graph --max-count=$cnt "$repo/$branch"

fi

