#!/bin/sh


#current branch
currBranch=`git rev-parse --abbrev-ref HEAD`

if [ "$1" == "" ]; then

git fetch origin "$currBranch"

git log --pretty=format:"%h - %an, %ar : %s" --graph "origin/$currBranch"

else

git log --pretty=format:"%h - %an, %ar : %s" --graph --max-count=$1 "origin/$currBranch"

fi

