#!/bin/sh -x

#squash merge into a tracking branch

SQ="Squash"

FB="$1"
if [ "$FB" == "" ]; then
  echo "Missing Feature Branch."
  exit
fi

TB="$2"
if [ "$TB" == "" ]; then
  echo "Missing Tracking Branch."
  exit
fi

#master#{{{

git checkout master
git fetch origin master
git reset --hard upstream/master
git clean -fxd
git push origin master
git merge upstream/master

#master#}}}
#feature branch

git checkout $FB
git rebase master

#feature branch
#squash

git checkout -b $FB$SQ master
#in case already created
git checkout $FB$SQ
git reset --hard master
#do the squash
git rebase -i $FB

#squash

