#!/bin/sh -x

#squash merge into a tracking branch

SQ="Squash"

FB="$1"
if [ "$FB" == "" ]; then
  echo "Missing Feature Branch."
  exit
fi

#master#{{{

git checkout master
git fetch origin master
git reset --hard upstream/master
git clean -fxd
git push origin master
git merge upstream/master

SHA=`git log --pretty=format:"%h - %an, %ar : %s" --max-count=1|cut -d' ' -f1`

#master#}}}
#feature branch#{{{

git checkout $FB
git rebase master

#CNT=`git log \
#  --pretty=format:"%h - %an, %ar : %s" \
#  --max-count=1000|grep -n "$SHA"|cut -d':' -f1`

#feature branch#}}}
#squash#{{{

#beg: old#{{{
#git checkout -b $FB$SQ master
##in case already created
#git checkout $FB$SQ
#git reset --hard master
#git clean -fxd
##do the squash
##git rebase -i $FB $SHA..
#git rebase -i $FB HEAD~$CNT
#end: old#}}}

git checkout -b $FB$SQ master
#in case already created
git checkout $FB$SQ
git reset --hard master
git clean -fxd
git merge --no-ff $FB
#do the squash
git rebase -i $SHA
#git rebase -i HEAD~$CNT

#squash#}}}

